export enum LocalizationKey {
  WELCOME = "welcome",
  HOME = "home",
  START = "start",
  LOADING = "loading",
  PROFILE = "profile",
  POST = "post",
  SEARCH = "search",
  FAVORITE = "favorite",
  LOGIN = "login",
  REGISTER = "register",
  LOGIN_WITH_ACCOUNT = "login with account",
  DONT_HAVE_ACCOUNT = "don't have account",
  HAVE_ACCOUNT = "have account",
  REGISTER_NOW = "register now",
  LOGIN_NOW = "login now",
  WELCOME_BACK = "welcome back",
  ENTER_LOGIN = "enter login",
  ENTER_REGISTER = "enter register",
  EMAIL = "email",
  PASSWORD = "password",
  FORGOT_PASSWORD = "forgot password",
  LAST_NAME = "last name",
  FIRST_NAME = "first name",
}
